### PR TITLE
Auto refresh token

### PR DESCRIPTION
**Pull request by fsufyan**

### CODE REVIEW

**Comment by fsufyan** [comment]
@lugehorsam

**Comment by lugehorsam** [comment]
Is the actual auto refreshing per request going to land in a separate PR? @fsufyan

**Comment by fsufyan** [comment]
> Is the actual auto refreshing per request going to land in a separate PR? @fsufyan

It's already applied in second commit, or am i missing something?

**Review by lugehorsam — APPROVED** [review]
Sorry the `GrpcClient.swift` file was collapsed so I missed it!

**Pull request merged**
