### PR TITLE
Add support for RPC calls from client.

### PR DESCRIPTION
**Pull request by fsufyan**

### CODE REVIEW

**Comment by fsufyan** [comment]
@lugehorsam Tests are omitted here, since it would fail without a server side function to call.
If it's necessary i can push it in new commit.

**Comment by lugehorsam** [comment]
@fsufyan I think it'd be worth adding a couple tests against these server side functions:

https://github.com/heroiclabs/nakama/tree/master/data/modules

Our SDK test suites run with the expectation of server side code loaded so that is fine.

**Comment by fsufyan** [comment]
@lugehorsam Tests has been added, please check and advise.

**Review by lugehorsam — APPROVED** [review]
👍 thanks

**Pull request merged**
