### PR TITLE
Fix package.swift with exact(), added  new methods blockFriends, banGroupUsers 

### PR DESCRIPTION
**Pull request by Allan-Nava**

### CODE REVIEW

**Comment by Allan-Nava** [comment]
Updated with new methods like in nakama-java

**Comment by Allan-Nava** [comment]
added a lot of methods for nakama client

**Comment by Allan-Nava** [comment]
@sesposito these are the features: 

1. added listUserGroups methods, 
2. listStorageObjects , 
3. listLeaderboardRecords , 
4. listChannelMessages , 
5. methods getUsers, 
6. importFacebookFriends, 
7. joinGroup, 
8. joinTournaments, 
9. fix swiftpackage manager 

Thanks in advance

**Comment by Allan-Nava** [comment]
> @sesposito these are the features:
> 
> 1. added listUserGroups methods,
> 2. listStorageObjects ,
> 3. listLeaderboardRecords ,
> 4. listChannelMessages ,
> 5. methods getUsers,
> 6. importFacebookFriends,
> 7. joinGroup,
> 8. joinTournaments,
> 9. fix swiftpackage manager
> 
> Thanks in advance

Any newss?  @mofirouz

**Comment by sesposito** [comment]
@Allan-Nava we really appreciate your contribution but please be patient, we'll review in due time.

**Comment by Allan-Nava** [comment]
> @Allan-Nava we really appreciate your contribution but please be patient, we'll review in due time.

Ok sorry

**Comment by Allan-Nava** [comment]
Added new methods with @toninospiderman123 to handle the storage

**Comment by Allan-Nava** [comment]
Any news?

**Comment by Allan-Nava** [comment]
News?

**Comment by Allan-Nava** [comment]
any news?

**Pull request closed without merging**
